Traceback (most recent call last):
  File "run_experiment_starling.py", line 124, in <module>
    shutil.rmtree(train_dir)
  File "/home/vladimirbenzen/miniconda3/lib/python3.7/shutil.py", line 485, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/home/vladimirbenzen/miniconda3/lib/python3.7/shutil.py", line 423, in _rmtree_safe_fd
    _rmtree_safe_fd(dirfd, fullname, onerror)
  File "/home/vladimirbenzen/miniconda3/lib/python3.7/shutil.py", line 427, in _rmtree_safe_fd
    onerror(os.rmdir, fullname, sys.exc_info())
  File "/home/vladimirbenzen/miniconda3/lib/python3.7/shutil.py", line 425, in _rmtree_safe_fd
    os.rmdir(entry.name, dir_fd=topfd)
OSError: [Errno 39] Directory not empty: 'bRDNs'
tar: experiment*: Cannot stat: No such file or directory
tar: Exiting with failure status due to previous errors

